name: Build and test Absytree
on: push

jobs:
  build-desktop:
    name: Build desktop version
    runs-on: ubuntu-latest
    container:
      image: nimlang/nim:2.0.0-regular
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: add Absytree as git safe.directory so nimble can install stuff
        run: git config --global --add safe.directory /__w/Absytree/Absytree
      - name: nimble setup
        run: PATH=/github/home/.nimble/bin:$PATH nimble setup

      - name: nimble buildDesktop
        run: nimble buildDesktop
        continue-on-error: true
      - name: nimble buildBrowser
        run: nimble buildBrowser
        continue-on-error: true
      - name: nimble buildAbsytreeServer
        run: nimble buildAbsytreeServer
        continue-on-error: true
      - name: nimble buildNimsuggestWS
        run: nimble buildNimsuggestWS
        continue-on-error: true

      - name: Run tests
        run: testament --print category unit
      - name: Build test report
        run: testament html
