name: Build desktop version
on: push

jobs:
  build-desktop:
    name: Build desktop version
    runs-on: ubuntu-latest
    container:
      image: nimlang/nim:2.0.0-regular
      volumes:
        - my-app:/app
    steps:
      - name: Test123
        run: nim
